services:

  mongo:
    build: ./mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    networks:
      - burguer-app-network
  
  auth-service:
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
  
  user-service:
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI} 
  
  order-service:
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
    
  product-service:
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}

volumes:
  mongo-data: