name: Test Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-auth-service:
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.7'

      - name: Install dependencies
        working-directory: burguer-app/auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: burguer-app/auth-service
        run: |
          pytest -v
  test-product-service:
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.7'
  
      - name: Install dependencies
        working-directory: burguer-app/product-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: burguer-app/product-service
        run: |
          pytest -v
  test-user-service:
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.7'
  
      - name: Install dependencies
        working-directory: burguer-app/user-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: burguer-app/user-service
        run: |
          pytest -v